[versions]
kotlin = "2.3.21"
kotlin-html = "0.12.0"
ktor = "3.4.3"
logback = "1.5.32"
warden-supreme = "1.0.0"
vck = "6.0.0-SNAPSHOT"
signum = "3.21.0"
exposed = "1.2.0"
h2 = "2.4.240"
pgsql = "42.7.7"
json = "1.11.0"
napier = "2.7.1"

[libraries]
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "json" }
kotlin-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlin-html" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
ktor-serverCore = { module = "io.ktor:ktor-server-core-jvm", version.ref = "ktor" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty-jvm", version.ref = "ktor" }
ktor-serverTestHost = { module = "io.ktor:ktor-server-test-host-jvm", version.ref = "ktor" }
ktor-html = { module = "io.ktor:ktor-server-html-builder-jvm", version.ref = "ktor" }
ktor-yaml = { module = "io.ktor:ktor-server-config-yaml", version.ref = "ktor" }
warden-supreme = { module = "at.asitplus.warden:supreme-verifier", version.ref = "warden-supreme" }
vck = { group = "at.asitplus.wallet", name = "vck", version.ref = "vck" }
vck-openid = { group = "at.asitplus.wallet", name = "vck-openid", version.ref = "vck" }
signum = { group = "at.asitplus.signum", name = "indispensable", version.ref = "signum" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "pgsql" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
